spring.application.name=rss

spring.datasource.url=jdbc:postgresql://localhost:5432/Rss_reader

spring.flyway.enabled=true

spring.datasource.username=edit_username
spring.datasource.password=edit_password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

brightdata.api.token=
brightdata.zone=
brightdata.api.url=https://api.brightdata.com/request
