
CREATE TABLE users (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       email VARCHAR(320) NOT NULL UNIQUE,
                       password_hash VARCHAR(255) NOT NULL,
                       created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE feed_sources (
                              id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              user_id BIGINT NOT NULL REFERENCES users (id) ON DELETE CASCADE,
                              name VARCHAR(255) NOT NULL,
                              url VARCHAR(2048) NOT NULL,
                              is_active_for_scheduler BOOLEAN NOT NULL DEFAULT TRUE,
                              created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                              last_fetched_at TIMESTAMPTZ,
                              CONSTRAINT uq_feed_sources_user_url UNIQUE (user_id, url)
);

CREATE TABLE articles (
                          id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                          feed_source_id BIGINT NOT NULL REFERENCES feed_sources (id) ON DELETE CASCADE,
                          guid VARCHAR(2048),
                          title TEXT NOT NULL,
                          link VARCHAR(2048) NOT NULL,
                          description TEXT,
                          published_at TIMESTAMPTZ,
                          full_text TEXT,
                          full_text_fetched_at TIMESTAMPTZ,
                          created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE preference_versions (
                                     id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                     feed_source_id BIGINT NOT NULL REFERENCES feed_sources (id) ON DELETE CASCADE,

                                     version_number INTEGER NOT NULL CHECK (version_number > 0),

                                     language VARCHAR(16) NOT NULL,
                                     summary_length VARCHAR(16) NOT NULL,
                                     style VARCHAR(32) NOT NULL ,

                                     original_content TEXT,
                                     processed_content TEXT,

                                     created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
                                     CONSTRAINT uq_preference_versions_source_number UNIQUE (feed_source_id, version_number),

                                     CONSTRAINT ck_pref_content_consistent CHECK (
                                         (original_content  IS NULL OR btrim(original_content)  <> '')
                                             AND (processed_content IS NULL OR btrim(processed_content) <> '')
                                             AND (processed_content IS NULL OR original_content IS NOT NULL)
                                         )
);

CREATE TABLE article_summaries (
                                   id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                                   article_id BIGINT NOT NULL REFERENCES articles (id) ON DELETE CASCADE,
                                   preference_version_id BIGINT NOT NULL REFERENCES preference_versions (id) ON DELETE CASCADE,
                                   status VARCHAR(16) NOT NULL CHECK (status IN ('OK', 'HIDDEN', 'FAILED')),

                                   generated_title TEXT,
                                   summary_text TEXT,
                                   hidden_reason TEXT,
                                   model_name VARCHAR(255),
                                   created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,

                                   CONSTRAINT uq_article_summaries_article_preference
                                       UNIQUE (article_id, preference_version_id),

                                   CONSTRAINT ck_article_summaries_result CHECK (
                                       status = 'FAILED'
                                           OR (status = 'OK' AND summary_text IS NOT NULL)
                                           OR (status = 'HIDDEN' AND hidden_reason IS NOT NULL)
                                       )
);

CREATE UNIQUE INDEX uq_articles_source_guid
    ON articles (feed_source_id, guid) WHERE guid IS NOT NULL;